export const GAME_REQUEST = "GAME_REQUEST";

export const GAME_FAILURE ="GAME_FAILURE";
export const POST_GAME_SUCCESS= "POST_GAME_SUCCESS";
export const GET_GAME_SUCCESS= "GET_GAME_SUCCESS";

export const PATCH_GAME_SUCCESS="PATCH_GAME_SUCCESS"


export const USER_REQUEST = "USER_REQUEST";
export const USER_FAILURE ="USER_FAILURE";

export const GET_USER_SUCCESS= "GET_USER_SUCCESS";



//For Authentication...
export const LOGIN_POST_REQUEST= "LOGIN_POST_REQUEST";
export const LOGIN_POST_SUCCESS= "LOGIN_POST_SUCCESS";
export const LOGIN_POST_FAILURE= "LOGIN_POST_FAILURE";
export const REGISTER_POST_SUCCESS= "LOGIN_POST_SUCCESS";



//For Wishlist...
export const WISHLIST_POST_REQUEST= "WISHLIST_POST_REQUEST";
export const WISHLIST_POST_FAILURE= "WISHLIST_POST_FAILURE";
export const WISHLIST_POST_SUCCESS= "WISHLIST_POST_SUCCESS";
export const WISHLIST_DELETE_SUCCESS= "WISHLIST_DELETE_SUCCESS";
export const WISHLIST_GET_SUCCESS= "WISHLIST_GET_SUCCESS";



//For Bag...
export const BAG_REQUEST = "BAG_REQUEST";
export const BAG_FAILURE = "BAG_FAILURE";

export const BAG_POST_SUCCESS = "BAG_POST_SUCCESS";
export const BAG_GET_SUCCESS = "BAG_GET_SUCCESS";
export const BAG_DELETE_SUCCESS = "BAG_DELETE_SUCCESS";
