export const GAME_REQUEST = "GAME_REQUEST";
export const GAME_DELETE = "GAME_DELETE";

export const GAME_FAILURE ="GAME_FAILURE";
export const POST_GAME_SUCCESS= "POST_GAME_SUCCESS";
export const GET_GAME_SUCCESS= "GET_GAME_SUCCESS";

export const PATCH_GAME_SUCCESS="PATCH_GAME_SUCCESS"


export const USER_REQUEST = "USER_REQUEST";
export const USER_FAILURE ="USER_FAILURE";

export const GET_USER_SUCCESS= "GET_USER_SUCCESS";



//For Authentication...
export const LOGIN_POST_REQUEST= "LOGIN_POST_REQUEST";
export const LOGIN_POST_SUCCESS= "LOGIN_POST_SUCCESS";
export const LOGIN_POST_FAILURE= "LOGIN_POST_FAILURE";
export const REGISTER_POST_SUCCESS= "LOGIN_POST_SUCCESS";

